name: Whisper to VTT

on: push

jobs:
  whisper:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1


    - uses: actions/setup-python@v5     
    
    - name: Ensure FFmpeg
      run: |
        if ! command -v ffmpeg >/dev/null 2>&1; then
          echo "FFmpeg not found, installing..."         
          sudo apt-get install -y ffmpeg
        else
          echo "FFmpeg already installed, skipping."
        fi

    - name: Install Whisper
      run: pip install openai-whisper

    - name: Generate same-name VTT
      run: |
        mkdir -p output
        whisper audio/bb.mp3 \
          --language ja \
          --model base \
          --output_format vtt \
          --output_dir output

    - name: Upload VTT
      uses: actions/upload-artifact@v4
      with:
        name: vtt
        path: output/bb.vtt
